// <auto-generated />
namespace Lexicon_LMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Documents2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Documents2));
        
        string IMigrationMetadata.Id
        {
            get { return "201602231552565_Documents2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
